name: prueba_tecnica_exito
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.8.1

dependencies:
    dio: ^5.8.0+1
    equatable: ^2.0.7
    flutter:
        sdk: flutter
    flutter_bloc: ^9.1.1
    flutter_dotenv: ^5.2.1
    get_it: ^8.0.3
    go_router: ^16.0.0
    intl: ^0.20.2

dev_dependencies:
    dart_code_linter: ^3.0.0
    flutter_lints: ^5.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - "assets/"
        # - "assets/img/"
        # - "assets/icons/"
    fonts:
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Medium.ttf
              - asset: assets/fonts/Roboto-Bold.ttf
              - asset: assets/fonts/Roboto-Italic.ttf
                style: italic
              - asset: assets/fonts/Roboto-BoldItalic.ttf
                weight: 700
                style: italic
        - family: RobotoCondensed
          fonts:
              - asset: assets/fonts/Roboto_Condensed-Regular.ttf
              - asset: assets/fonts/Roboto_Condensed-Bold.ttf
              - asset: assets/fonts/Roboto_Condensed-Italic.ttf
                style: italic
              - asset: assets/fonts/Roboto_Condensed-BoldItalic.ttf
                weight: 700
                style: italic
